# Generated by Django 5.2.16 on 2026-08-27 15:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tip_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('species', models.CharField(choices=[('all', 'All Species'), ('poultry', 'Poultry'), ('cattle', 'Cattle'), ('goat', 'Goat'), ('sheep', 'Sheep')], default='all', max_length=20)),
                ('season', models.CharField(blank=True, default='', max_length=20)),
                ('language', models.CharField(default='en', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
