# Generated by Django 5.2.16 on 2026-08-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_verification_token_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Administrator'), ('SYSTEM_ADMIN', 'System Administrator'), ('CLINIC_ADMIN', 'Clinic Administrator'), ('VETERINARIAN', 'Veterinarian'), ('VET_TECHNICIAN', 'Veterinary Technician'), ('FARMER', 'Farmer'), ('LAB_STAFF', 'Laboratory Staff'), ('PHARMACIST', 'Pharmacist'), ('RECEPTIONIST', 'Receptionist'), ('INSURANCE_PROVIDER', 'Insurance Provider'), ('GOVERNMENT_OFFICER', 'Government Officer / Epidemiologist')], db_index=True, default='FARMER', max_length=30),
        ),
    ]
