# Generated by Django 5.2.16 on 2026-08-01 19:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('report_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('species', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=255)),
                ('affected', models.PositiveIntegerField(default=0)),
                ('dead', models.PositiveIntegerField(default=0)),
                ('signs', models.JSONField(default=list)),
                ('date', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('lga', models.CharField(db_index=True, max_length=100)),
                ('coords', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmer_name', models.CharField(blank=True, default='', max_length=255)),
                ('alert_status', models.CharField(choices=[('Suspected', 'Suspected'), ('Under investigation', 'Under investigation'), ('Confirmed', 'Confirmed'), ('Closed', 'Closed')], db_index=True, default='Suspected', max_length=30)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disease_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
