# Generated by Django 5.2.16 on 2026-08-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasereport',
            name='photos',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
