# Generated by Django 5.2.16 on 2026-08-27 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_diseasereport_photos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diseasereport',
            index=models.Index(fields=['alert_status', '-submitted_at'], name='idx_disease_status_date'),
        ),
        migrations.AddIndex(
            model_name='diseasereport',
            index=models.Index(fields=['species', 'alert_status'], name='idx_disease_species_status'),
        ),
        migrations.AddIndex(
            model_name='diseasereport',
            index=models.Index(fields=['lga', '-submitted_at'], name='idx_disease_lga_date'),
        ),
    ]
