# Generated by Django 5.2.16 on 2026-08-27 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_add_passport_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('api_key', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LivestockInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('policy_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Claimed', 'Claimed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='patients.patient')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_insurance', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.insuranceprovider')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['owner', 'status'], name='idx_insurance_owner_status'), models.Index(fields=['animal', 'status'], name='idx_insurance_animal_status')],
            },
        ),
    ]
