# Generated by Django 5.2.16 on 2026-08-01 19:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VeterinarianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vet_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=255)),
                ('specializations', models.JSONField(default=list)),
                ('species_treated', models.JSONField(default=list)),
                ('diseases_expertise', models.JSONField(default=list)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('languages', models.JSONField(default=list)),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_address', models.TextField()),
                ('lga', models.CharField(db_index=True, max_length=100)),
                ('service_area', models.JSONField(default=list)),
                ('whatsapp_number', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('available_online', models.BooleanField(default=True)),
                ('available_emergency', models.BooleanField(default=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('total_consultations', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_initials', models.CharField(blank=True, default='', max_length=5)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vet_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
