# Generated by Django 5.2.16 on 2026-08-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketplacebookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='marketplacecomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='marketplaceconversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='marketplacemessage',
            options={'ordering': ['created_at']},
        ),
    ]
