# Generated by Django 5.2.16 on 2026-08-01 19:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sample_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('species', models.CharField(max_length=100)),
                ('test', models.CharField(max_length=255)),
                ('facility', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('In analysis', 'In analysis'), ('Result ready', 'Result ready'), ('Published', 'Published')], db_index=True, default='Received', max_length=30)),
                ('priority', models.CharField(choices=[('Urgent', 'Urgent'), ('Routine', 'Routine')], db_index=True, default='Routine', max_length=20)),
                ('date_received', models.CharField(max_length=20)),
                ('patient_id_str', models.CharField(blank=True, default='', max_length=50)),
                ('requested_by', models.CharField(blank=True, default='', max_length=255)),
                ('result_findings', models.TextField(blank=True, default='')),
                ('result_positive', models.BooleanField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_samples', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
