# Generated by Django 5.2.16 on 2026-08-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='labsample',
            index=models.Index(fields=['status', '-date_received'], name='idx_lab_status_date'),
        ),
        migrations.AddIndex(
            model_name='labsample',
            index=models.Index(fields=['priority', 'status'], name='idx_lab_priority_status'),
        ),
    ]
