# Generated by Django 5.2.16 on 2026-08-27 14:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('species', models.CharField(db_index=True, max_length=100)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('dose_number', models.PositiveIntegerField(default=1)),
                ('age_days', models.PositiveIntegerField(default=0)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['species', 'age_days'],
                'indexes': [models.Index(fields=['species', 'is_active'], name='idx_vax_template_species')],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('record_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('animal_name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=100)),
                ('vaccine_name', models.CharField(max_length=255)),
                ('dose_number', models.PositiveIntegerField(default=1)),
                ('date_given', models.DateField(default=django.utils.timezone.now)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, default='', max_length=255)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_given'],
                'indexes': [models.Index(fields=['owner', '-date_given'], name='idx_vaxrecord_owner_date'), models.Index(fields=['next_due_date', 'reminder_sent'], name='idx_vaxrecord_due_remind')],
            },
        ),
    ]
