# Generated by Django 5.2.16 on 2026-08-01 19:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veterinarians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('consultation_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('farmer_name', models.CharField(max_length=255)),
                ('farm_location', models.CharField(max_length=255)),
                ('vet_id_str', models.CharField(blank=True, default='', max_length=50)),
                ('vet_name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('in-app', 'In-App'), ('whatsapp', 'WhatsApp')], default='in-app', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In progress', 'In progress'), ('Resolved', 'Resolved'), ('Cancelled', 'Cancelled')], db_index=True, default='Pending', max_length=20)),
                ('disease_name', models.CharField(blank=True, default='', max_length=255)),
                ('symptoms_en', models.TextField(blank=True, default='')),
                ('symptoms_ha', models.TextField(blank=True, default='')),
                ('species', models.CharField(max_length=100)),
                ('breed', models.CharField(blank=True, default='', max_length=100)),
                ('animal_age', models.CharField(max_length=100)),
                ('animal_gender', models.CharField(default='Mixed', max_length=20)),
                ('affected_count', models.PositiveIntegerField(default=1)),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('severity', models.CharField(choices=[('Mild', 'Mild'), ('Moderate', 'Moderate'), ('Severe', 'Severe'), ('Critical', 'Critical')], default='Moderate', max_length=20)),
                ('additional_notes', models.TextField(blank=True, default='')),
                ('photo_urls', models.JSONField(default=list)),
                ('video_urls', models.JSONField(default=list)),
                ('voice_urls', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='veterinarians.veterinarianprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('sender', models.CharField(choices=[('farmer', 'Farmer'), ('vet', 'Veterinarian')], max_length=20)),
                ('sender_name', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(blank=True, max_length=20, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='consultations.consultationrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
