# Generated by Django 5.2.16 on 2026-08-27 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultationrequest_farmer'),
        ('veterinarians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['consultation', '-sent_at'], name='idx_msg_consult_date'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['read', '-sent_at'], name='idx_msg_read_date'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['status', '-submitted_at'], name='idx_consult_status_date'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['farmer', 'status'], name='idx_consult_farmer_status'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['vet', 'status'], name='idx_consult_vet_status'),
        ),
        migrations.AddIndex(
            model_name='consultationrequest',
            index=models.Index(fields=['severity', 'status'], name='idx_consult_severity_status'),
        ),
    ]
