# Generated by Django 5.2.16 on 2026-08-08 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='ERROR', max_length=16)),
                ('category', models.CharField(choices=[('API', 'API'), ('AUTH', 'Authentication'), ('PERMISSION', 'Permission'), ('DB', 'Database'), ('FILE_UPLOAD', 'File Upload'), ('PAYMENT', 'Payment'), ('AI', 'AI Service'), ('CHAT', 'Chat'), ('WEBSOCKET', 'WebSocket'), ('PERFORMANCE', 'Performance'), ('SECURITY', 'Security'), ('FORMS', 'Form / Validation'), ('REACT', 'Frontend Runtime'), ('JS', 'Frontend JavaScript'), ('TASK', 'Background Task'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=32)),
                ('source', models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('EXTERNAL', 'External Service')], db_index=True, default='BACKEND', max_length=16)),
                ('module', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('endpoint', models.CharField(blank=True, default='', max_length=500)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_role', models.CharField(blank=True, default='', max_length=30)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('exception_type', models.CharField(blank=True, default='', max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('stack_trace', models.TextField(blank=True, default='')),
                ('environment', models.CharField(blank=True, default='', max_length=32)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolution_status', models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('IGNORED', 'Ignored')], db_index=True, default='NEW', max_length=16)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_errors', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='ERROR', max_length=16)),
                ('category', models.CharField(choices=[('API', 'API'), ('AUTH', 'Authentication'), ('PERMISSION', 'Permission'), ('DB', 'Database'), ('FILE_UPLOAD', 'File Upload'), ('PAYMENT', 'Payment'), ('AI', 'AI Service'), ('CHAT', 'Chat'), ('WEBSOCKET', 'WebSocket'), ('PERFORMANCE', 'Performance'), ('SECURITY', 'Security'), ('FORMS', 'Form / Validation'), ('REACT', 'Frontend Runtime'), ('JS', 'Frontend JavaScript'), ('TASK', 'Background Task'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=32)),
                ('module', models.CharField(blank=True, default='', max_length=255)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('error', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.errorlog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=16)),
                ('source', models.CharField(choices=[('FRONTEND', 'Frontend'), ('BACKEND', 'Backend'), ('EXTERNAL', 'External Service')], default='BACKEND', max_length=16)),
                ('module', models.CharField(blank=True, default='', max_length=255)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='errorlog',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='monitoring.incident'),
        ),
        migrations.CreateModel(
            name='IncidentRCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('impact', models.TextField(blank=True, default='')),
                ('fix', models.TextField(blank=True, default='')),
                ('preventive_action', models.TextField(blank=True, default='')),
                ('related_deployment', models.CharField(blank=True, default='', max_length=255)),
                ('related_commit', models.CharField(blank=True, default='', max_length=255)),
                ('lessons_learned', models.TextField(blank=True, default='')),
                ('documented_at', models.DateTimeField(auto_now=True)),
                ('documented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documented_rcas', to=settings.AUTH_USER_MODEL)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rca', to='monitoring.incident')),
            ],
            options={
                'verbose_name': 'Root Cause Analysis',
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=16)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_updates', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='monitoring.incident')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(editable=False, max_length=32, unique=True)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('ACCOUNT', 'Account'), ('PATIENT', 'Patient'), ('APPOINTMENT', 'Appointment'), ('CONSULTATION', 'Consultation'), ('LAB', 'Laboratory'), ('SURVEILLANCE', 'Surveillance'), ('BILLING', 'Billing'), ('PAYMENT', 'Payment'), ('WITHDRAWAL', 'Withdrawal'), ('MARKETPLACE', 'Marketplace'), ('COMMUNITY', 'Community'), ('CHAT', 'Chat'), ('AI', 'AI Service'), ('VETERINARIAN', 'Veterinarian'), ('FARMER', 'Farmer'), ('DRUG', 'Pharmacy'), ('ADMIN', 'Administration'), ('SECURITY', 'Security'), ('SYSTEM', 'System')], db_index=True, default='SYSTEM', max_length=32)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('actor_role', models.CharField(blank=True, default='', max_length=30)),
                ('target_type', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['timestamp', 'severity'], name='monitoring__timesta_b5b24d_idx'),
        ),
        migrations.AddIndex(
            model_name='errorlog',
            index=models.Index(fields=['correlation_id', 'timestamp'], name='monitoring__correla_2f7b35_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['category', 'timestamp'], name='monitoring__categor_339acf_idx'),
        ),
        migrations.AddIndex(
            model_name='systemevent',
            index=models.Index(fields=['actor', 'timestamp'], name='monitoring__actor_i_a9e369_idx'),
        ),
    ]
