# Generated by Django 5.2.16 on 2026-08-27 14:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veterinarians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VetAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='veterinarians.veterinarianprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='VetBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('booking_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('animal_name', models.CharField(max_length=255)),
                ('species', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No show', 'No show')], db_index=True, default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('availability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='vet_bookings.vetavailability')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_bookings', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='veterinarians.veterinarianprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vetavailability',
            index=models.Index(fields=['vet', 'date', 'is_booked'], name='idx_vet_avail_vet_date'),
        ),
        migrations.AddIndex(
            model_name='vetbooking',
            index=models.Index(fields=['farmer', 'status'], name='idx_vetbook_farmer_status'),
        ),
        migrations.AddIndex(
            model_name='vetbooking',
            index=models.Index(fields=['vet', 'status'], name='idx_vetbook_vet_status'),
        ),
    ]
