# Generated by Django 5.2.16 on 2026-08-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugstock',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='drugstock',
            name='facility_lga',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drugstock',
            name='facility_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='drugstock',
            name='facility_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='drugstock',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drugstock',
            name='last_restocked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='drugstock',
            index=models.Index(fields=['name', 'facility_lga'], name='idx_drug_name_lga'),
        ),
        migrations.AddIndex(
            model_name='drugstock',
            index=models.Index(fields=['category', 'is_available'], name='idx_drug_cat_avail'),
        ),
        migrations.AddIndex(
            model_name='drugstock',
            index=models.Index(fields=['facility_lga', 'is_available'], name='idx_drug_lga_avail'),
        ),
    ]
