# Generated by Django 5.2.16 on 2026-08-01 19:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('appointment_code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('patient_id_str', models.CharField(blank=True, default='', max_length=50)),
                ('time', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=255)),
                ('animal', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Scheduled', max_length=20)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='patients.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
