# Generated by Django 5.2.16 on 2026-08-28 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('message', 'Text'), ('image', 'Image'), ('video', 'Video'), ('voice', 'Voice note'), ('audio', 'Audio'), ('document', 'Document'), ('animal', 'Animal photo/info'), ('lab_record', 'Laboratory record'), ('disease_report', 'Disease report'), ('prescription', 'Prescription'), ('location', 'Location'), ('system', 'System')], db_index=True, default='message', max_length=30),
        ),
    ]
